#
#   This is the core configuration for a configuration service.  I have two examples here:
#
#       -  A configuration service which completelty loads the configuration for the services
#          from the local file server of the config service.  This should only be used for
#          demonstration purposes or for a small application with a limited number of services.
#
#       -  A configuraton service that uses a git-based repository to read the files from
#


####################################
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/klimtever/config-repo/
          searchPaths: licensingservice, organizationservice
          # username: native-cloud-apps
          # password: 0ffended
          # uri: https://github.com/LeeKyoungIl/spring-cloud-config-repository
        native:
          #  searchLocations: file://<chapter 6>/confsvr/src/main/resources/config/licensingservice,
          #                   file://<chapter 6>confsvr/src/main/resources/config/organizationservice
          searchLocations: file:///src/test/java/spring-msa-ws/chapter6/confsvr/src/main/resources/config/licensingservice,
                           file:///src/test/java/spring-msa-ws/chapter6/confsvr/src/main/resources/config/organizationservice,
##              #searchLocations: classpath:config/,classpath:config/licensingservice

management:
  security:
    enabled: false

####
#Classpath and file-based solution
####

# server:
#   port: 8888
# spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#             #  searchLocations: file://<chapter 6>/confsvr/src/main/resources/config/licensingservice,
#             #                   file://<chapter 6>confsvr/src/main/resources/config/organizationservice
#             searchLocations: file:///src/test/java/spring-msa-ws/chapter6/confsvr/src/main/resources/config/licensingservice
# ##              #searchLocations: classpath:config/,classpath:config/licensingservice

#         # native:
